In [4]:
import numpy as np
A = np.array([[1,  1,  1,   1,    1,    32,      32,    0],
                   [0,  1,  -1,  2,   -2,   16,   -16,   0],
                   [0,  1,  1,   4,    4,   8,    8,   0],
                   [0,  1,  -1,  8,   -8,   4,   -4,   0],
                   [0,  1,  1,   16,  16,   2,  2,   0],
                   [0,  1,  -1,  32,  -32,  1,  -1,  1]],
                  dtype=np.float32).T

In [5]:
A.T.shape

(6, 8)

In [21]:
X = np.random.random((8, 8))
A.T.dot(X).dot(A)

array([[  2.12884521e+03,   3.03141530e+02,   8.86917739e+02,
          2.36407740e+02,   1.47201471e+03,   7.11062455e+02],
       [  6.59219339e+01,   1.44126897e+02,  -3.02584170e+01,
          7.23021148e+01,  -1.70302707e+02,   1.37888037e+02],
       [  7.96183067e+02,   8.48405363e+01,   3.28337077e+02,
          6.13196286e+01,   5.46903503e+02,   1.83489950e+02],
       [ -2.04996207e+02,   1.39814577e+02,  -6.19755312e+01,
          9.09655172e+01,  -4.68622166e+01,   2.48146190e+02],
       [  1.17809673e+03,   2.81994201e+01,   4.68009437e+02,
          1.00175982e+00,   7.62340649e+02,  -4.25553937e+00],
       [ -9.54482977e+02,   4.37755104e+02,  -2.26683174e+02,
          2.99595051e+02,   9.39343954e+00,   8.63935509e+02]])

In [50]:
A.T

array([[  1.,   1.,   1.,   1.,   1.,  32.,  32.,   0.],
       [  0.,   1.,  -1.,   2.,  -2.,  16., -16.,   0.],
       [  0.,   1.,   1.,   4.,   4.,   8.,   8.,   0.],
       [  0.,   1.,  -1.,   8.,  -8.,   4.,  -4.,   0.],
       [  0.,   1.,   1.,  16.,  16.,   2.,   2.,   0.],
       [  0.,   1.,  -1.,  32., -32.,   1.,  -1.,   1.]], dtype=float32)

In [55]:
def A_T_dot_X(X):
    m1_add_m2 = X[1] + X[2]
    m1_sub_m2 = X[1] - X[2]
    m3_add_m4 = X[3] + X[4]
    m3_sub_m4 = X[3] - X[4]
    m5_add_m6 = X[5] + X[6]
    m5_sub_m6 = X[5] - X[6]
    s0 = X[0] + m1_add_m2
    s5 = X[7] + m1_sub_m2
    s1 = m1_sub_m2 + m5_sub_m6 * 16
    s4 = m1_add_m2 + m3_add_m4 * 16    
    s2 = m1_add_m2 + 8 * m5_add_m6
    s3 = m1_sub_m2 + 8 * m3_sub_m4
    s0 = s0 + m5_add_m6 * 32
    s5 = s5 + m3_sub_m4 * 32
    s1 = s1 + m3_sub_m4 * 2
    s4 = s4 + m5_add_m6 * 2
    s0 = s0 + m3_add_m4
    s5 = s5 + m5_sub_m6
    s2 = s2 + m3_add_m4 * 4
    s3 = s3 + m5_sub_m6 * 4

    result = np.zeros((6, s0.size))
    result[0] = s0
    result[1] = s1
    result[2] = s2
    result[3] = s3
    result[4] = s4
    result[5] = s5
    return result

In [56]:
A

array([[  1.,   0.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,  -1.,   1.,  -1.,   1.,  -1.],
       [  1.,   2.,   4.,   8.,  16.,  32.],
       [  1.,  -2.,   4.,  -8.,  16., -32.],
       [ 32.,  16.,   8.,   4.,   2.,   1.],
       [ 32., -16.,   8.,  -4.,   2.,  -1.],
       [  0.,   0.,   0.,   0.,   0.,   1.]], dtype=float32)

In [57]:
def X_dot_A(X):
    return A_T_dot_X(X.T).T


In [58]:
np.testing.assert_allclose(
    A_T_dot_X(X), 
    A.T.dot(X), 
    atol=1e-3, rtol=1e-3)

In [59]:
np.testing.assert_allclose(
    X_dot_A(A_T_dot_X(X)),
    A.T.dot(X).dot(A), atol=1e-3, rtol=1e-3)