In [1]:
from __future__ import division
import numpy as np
A = np.array([[1,  1,  1,   1,    1,    32,      32,    0],
                   [0,  1,  -1,  2,   -2,   16,   -16,   0],
                   [0,  1,  1,   4,    4,   8,    8,   0],
                   [0,  1,  -1,  8,   -8,   4,   -4,   0],
                   [0,  1,  1,   16,  16,   2,  2,   0],
                   [0,  1,  -1,  32,  -32,  1,  -1,  1]],
                  dtype=np.float32).T

In [2]:
A.T.shape

(6, 8)

In [3]:
X = np.random.random((8, 8))
A.T.dot(X).dot(A)

array([[ 2279.53672559,    93.14981548,   919.28517152,    64.98949035,
         1509.80438063,   202.92364418],
       [  816.63040044,    77.57190375,   177.49753447,    90.38036514,
          -49.68982707,   309.13935632],
       [  813.33920446,   -22.4939987 ,   343.60077889,    24.28173823,
          605.91112824,   126.33703776],
       [  171.29128917,    14.42990213,    16.31021885,    55.38060905,
         -104.7243629 ,   219.2474342 ],
       [ 1003.75478809,  -192.06978807,   476.39812445,    34.81571071,
          973.18319948,   327.49664857],
       [  -52.38459258,     6.26250189,   -85.0212656 ,   137.83380243,
         -338.10017994,   570.81380446]])

In [4]:
A.T

array([[  1.,   1.,   1.,   1.,   1.,  32.,  32.,   0.],
       [  0.,   1.,  -1.,   2.,  -2.,  16., -16.,   0.],
       [  0.,   1.,   1.,   4.,   4.,   8.,   8.,   0.],
       [  0.,   1.,  -1.,   8.,  -8.,   4.,  -4.,   0.],
       [  0.,   1.,   1.,  16.,  16.,   2.,   2.,   0.],
       [  0.,   1.,  -1.,  32., -32.,   1.,  -1.,   1.]], dtype=float32)

In [5]:
def A_T_dot_X(X):
    m1_add_m2 = X[1] + X[2]
    m1_sub_m2 = X[1] - X[2]
    m3_add_m4 = X[3] + X[4]
    m3_sub_m4 = X[3] - X[4]
    m5_add_m6 = X[5] + X[6]
    m5_sub_m6 = X[5] - X[6]
    s0 = X[0] + m1_add_m2
    s5 = X[7] + m1_sub_m2
    s1 = m1_sub_m2 + m5_sub_m6 * 16
    s4 = m1_add_m2 + m3_add_m4 * 16    
    s2 = m1_add_m2 + 8 * m5_add_m6
    s3 = m1_sub_m2 + 8 * m3_sub_m4
    s0 = s0 + m5_add_m6 * 32
    s5 = s5 + m3_sub_m4 * 32
    s1 = s1 + m3_sub_m4 * 2
    s4 = s4 + m5_add_m6 * 2
    s0 = s0 + m3_add_m4
    s5 = s5 + m5_sub_m6
    s2 = s2 + m3_add_m4 * 4
    s3 = s3 + m5_sub_m6 * 4

    result = np.zeros((6, s0.size))
    result[0] = s0
    result[1] = s1
    result[2] = s2
    result[3] = s3
    result[4] = s4
    result[5] = s5
    return result

In [6]:
A

array([[  1.,   0.,   0.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,  -1.,   1.,  -1.,   1.,  -1.],
       [  1.,   2.,   4.,   8.,  16.,  32.],
       [  1.,  -2.,   4.,  -8.,  16., -32.],
       [ 32.,  16.,   8.,   4.,   2.,   1.],
       [ 32., -16.,   8.,  -4.,   2.,  -1.],
       [  0.,   0.,   0.,   0.,   0.,   1.]], dtype=float32)

In [7]:
def X_dot_A(X):
    return A_T_dot_X(X.T).T


In [8]:
np.testing.assert_allclose(
    A_T_dot_X(X), 
    A.T.dot(X), 
    atol=1e-3, rtol=1e-3)

In [9]:
np.testing.assert_allclose(
    X_dot_A(A_T_dot_X(X)),
    A.T.dot(X).dot(A), atol=1e-3, rtol=1e-3)

In [10]:
B = np.array(
    [[1,   0,    -21/4,    0,    21/4,     0,    -1,  0],
     [0,   1,      1,    -17/4,  -17/4,    1,    1,   0],
     [0,   -1,     1,    17/4,   -17/4,   -1,    1,   0],
     [0,  1/2,    1/4,   -5/2,   -5/4,     2,    1,   0],
     [0,  -1/2,   1/4,    5/2,   -5/4,    -2,    1,   0],
     [0,   2,      4,    -5/2,    -5,     1/2,   1,   0],
     [0,   -2,     4,     5/2,    -5,    -1/2,   1,   0],
     [0,   -1,     0,    21/4,     0,    -21/4,  0,   1]],
    dtype=np.float32).T
print(B.T)

[[ 1.    0.   -5.25  0.    5.25  0.   -1.    0.  ]
 [ 0.    1.    1.   -4.25 -4.25  1.    1.    0.  ]
 [ 0.   -1.    1.    4.25 -4.25 -1.    1.    0.  ]
 [ 0.    0.5   0.25 -2.5  -1.25  2.    1.    0.  ]
 [ 0.   -0.5   0.25  2.5  -1.25 -2.    1.    0.  ]
 [ 0.    2.    4.   -2.5  -5.    0.5   1.    0.  ]
 [ 0.   -2.    4.    2.5  -5.   -0.5   1.    0.  ]
 [ 0.   -1.    0.    5.25  0.   -5.25  0.    1.  ]]


In [29]:
def B_T_dot_X(X):
    wd0 = X[0] - X[6]
    d4_sub_d2 = X[4] - X[2]
    wd7 = X[7] - X[1]
    d3_sub_d5 = X[3] - X[5]
    wd1 = X[2] + X[6]
    wd2 = X[1] + X[5]
    wd4 = X[5] + X[1] * 0.25
    wd5 = X[6] - X[4] * 5
    wd3 = X[6] + X[2] * 0.25
    wd6 = X[1] + X[5] * 0.25
    
    wd0 = wd0 + d4_sub_d2 * 5.25
    wd7 = wd7 + d3_sub_d5 * 5.25

    wd1 = wd1 - X[4] * 4.25
    wd2 = wd2 - X[3] * 4.25
    
    wd3 = wd3 - X[4] * 1.25
    wd5 = wd5 + X[2] * 4
    wd4 = wd4 - X[3] * 1.25
    wd6 = wd6 - X[3] * 1.25
    
    result = np.zeros((8, wd0.size))
    result[0] = wd0
    result[1] = wd1 + wd2
    result[2] = wd1 - wd2
    result[3] = wd3 + wd4 * 2
    result[4] = wd3 - wd4 * 2
    result[5] = wd5 + wd6 * 2
    result[6] = wd5 - wd6 * 2
    result[7] = wd7
    return result

def X_dot_B(X):
    return B_T_dot_X(X.T).T


array([[-3.94160021, -0.39707211,  1.01389183, -1.89092649, -1.32468301,
         0.65130627,  2.25137927,  1.58388842],
       [-0.927845  , -3.85648272, -2.45472299, -1.10567028, -1.37867465,
        -3.68188496, -4.44220229, -3.22989566],
       [ 3.6436217 ,  2.29905905,  0.79407417,  1.36430156,  3.01882076,
         1.63750617,  0.20864486, -0.91902815],
       [ 0.47067339, -1.28780779, -0.6667518 ,  0.61877152,  0.02666682,
        -0.71142581, -1.21397208, -0.36787336],
       [ 1.62212386,  2.08941991,  1.21701949, -0.41964026,  1.51148966,
         1.28379597,  1.06256513, -0.78878458],
       [ 3.36634091, -0.18900032, -1.34327562,  1.84621704,  0.79028245,
        -1.85132437, -3.34341492, -0.9326498 ],
       [ 3.94908187,  0.94283735,  0.23997309,  1.86200372,  2.49727928,
         1.09198786, -1.09492655, -1.37155873],
       [ 1.09923203,  3.81003   ,  2.09334467, -1.21681923,  2.07160207,
         1.90959169,  2.56511021, -0.3970806 ]])

In [44]:
for i in range(10):
    X = np.random.random((8, 8))
    np.testing.assert_allclose(
        X_dot_B(B_T_dot_X(X)), 
        B.T.dot(X).dot(B), 
        atol=1e-7, rtol=1e-7)